/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.7 scene.gltf
Author: kking88gb (https://sketchfab.com/kking88gb)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/soler-panel-setup-087f976a313f401da2d38f0df73905ff
Title: soler panel setup
*/
'use client';


import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/scene.gltf')
  return (
    <group {...props} dispose={null}>
      <group position={[0.51, 1.777, -0.699]} rotation={[0.611, 0, 0]} scale={[0.992, 0.035, 1.7]}>
        <mesh geometry={nodes.Object_4.geometry} material={materials.material} />
        <mesh geometry={nodes.Object_5.geometry} material={materials['Material.001']} />
      </group>
      <group position={[1.52, 1.777, -0.699]} rotation={[0.611, 0, 0]} scale={[0.992, 0.035, 1.7]}>
        <mesh geometry={nodes.Object_7.geometry} material={materials['PV.001']} />
        <mesh geometry={nodes.Object_8.geometry} material={materials['Material.002']} />
      </group>
      <group position={[2.53, 1.777, -0.699]} rotation={[0.611, 0, 0]} scale={[0.992, 0.035, 1.7]}>
        <mesh geometry={nodes.Object_10.geometry} material={materials['PV.002']} />
        <mesh geometry={nodes.Object_11.geometry} material={materials['Material.003']} />
      </group>
      <group position={[0.51, 0.79, 0.71]} rotation={[0.611, 0, 0]} scale={[0.992, 0.035, 1.7]}>
        <mesh geometry={nodes.Object_13.geometry} material={materials['PV.005']} />
        <mesh geometry={nodes.Object_14.geometry} material={materials['Material.006']} />
      </group>
      <group position={[1.52, 0.79, 0.71]} rotation={[0.611, 0, 0]} scale={[0.992, 0.035, 1.7]}>
        <mesh geometry={nodes.Object_16.geometry} material={materials['PV.004']} />
        <mesh geometry={nodes.Object_17.geometry} material={materials['Material.005']} />
      </group>
      <group position={[2.53, 0.79, 0.71]} rotation={[0.611, 0, 0]} scale={[0.992, 0.035, 1.7]}>
        <mesh geometry={nodes.Object_19.geometry} material={materials['PV.003']} />
        <mesh geometry={nodes.Object_20.geometry} material={materials['Material.004']} />
      </group>
      <group position={[-2.53, 1.777, -0.699]} rotation={[0.611, 0, 0]} scale={[0.992, 0.035, 1.7]}>
        <mesh geometry={nodes.Object_22.geometry} material={materials['PV.011']} />
        <mesh geometry={nodes.Object_23.geometry} material={materials['Material.012']} />
      </group>
      <group position={[-1.52, 1.777, -0.699]} rotation={[0.611, 0, 0]} scale={[0.992, 0.035, 1.7]}>
        <mesh geometry={nodes.Object_25.geometry} material={materials['PV.010']} />
        <mesh geometry={nodes.Object_26.geometry} material={materials['Material.011']} />
      </group>
      <group position={[-0.51, 1.777, -0.699]} rotation={[0.611, 0, 0]} scale={[0.992, 0.035, 1.7]}>
        <mesh geometry={nodes.Object_28.geometry} material={materials['PV.009']} />
        <mesh geometry={nodes.Object_29.geometry} material={materials['Material.010']} />
      </group>
      <group position={[-0.51, 0.79, 0.71]} rotation={[0.611, 0, 0]} scale={[0.992, 0.035, 1.7]}>
        <mesh geometry={nodes.Object_31.geometry} material={materials['PV.008']} />
        <mesh geometry={nodes.Object_32.geometry} material={materials['Material.009']} />
      </group>
      <group position={[-1.52, 0.79, 0.71]} rotation={[0.611, 0, 0]} scale={[0.992, 0.035, 1.7]}>
        <mesh geometry={nodes.Object_34.geometry} material={materials['PV.007']} />
        <mesh geometry={nodes.Object_35.geometry} material={materials['Material.008']} />
      </group>
      <group position={[-2.53, 0.79, 0.71]} rotation={[0.611, 0, 0]} scale={[0.992, 0.035, 1.7]}>
        <mesh geometry={nodes.Object_37.geometry} material={materials['PV.006']} />
        <mesh geometry={nodes.Object_38.geometry} material={materials['Material.007']} />
      </group>
      <mesh geometry={nodes.Object_40.geometry} material={materials.tube} position={[-2.6, 1.23, -0.06]} rotation={[-0.96, 0, 0]} scale={[1, 2.86, 1]} />
      <mesh geometry={nodes.Object_42.geometry} material={materials.tube} position={[-2.6, 0.256, 0.92]} scale={[1, 0.51, 1]} />
      <mesh geometry={nodes.Object_44.geometry} material={materials.tube} position={[-2.6, 0.926, -1]} scale={[1, 1.84, 1]} />
      <mesh geometry={nodes.Object_46.geometry} material={materials.Tube_clamp} position={[0, 1.423, -0.263]} rotation={[0.611, 0, 0]} scale={[6.15, 0.03, 0.03]} />
      <mesh geometry={nodes.Object_48.geometry} material={materials.Tube_clamp} position={[0, 1.079, 0.229]} rotation={[0.611, 0, 0]} scale={[6.15, 0.03, 0.03]} />
      <mesh geometry={nodes.Object_50.geometry} material={materials.Tube_clamp} position={[0, 0.465, 1.105]} rotation={[0.611, 0, 0]} scale={[6.15, 0.03, 0.03]} />
      <mesh geometry={nodes.Object_52.geometry} material={materials.Tube_clamp} position={[0, 2.037, -1.139]} rotation={[0.611, 0, 0]} scale={[6.15, 0.03, 0.03]} />
      <mesh geometry={nodes.Object_54.geometry} material={materials.tube} position={[-2.6, 0.289, -0.05]} rotation={[1.302, 0, 0]} scale={[1, 1.88, 1]} />
      <mesh geometry={nodes.Object_56.geometry} material={materials.tube} position={[-0.8, 1.23, -0.06]} rotation={[-0.96, 0, 0]} scale={[1, 2.86, 1]} />
      <mesh geometry={nodes.Object_58.geometry} material={materials.tube} position={[-0.8, 0.256, 0.92]} scale={[1, 0.51, 1]} />
      <mesh geometry={nodes.Object_60.geometry} material={materials.tube} position={[-0.8, 0.926, -1]} scale={[1, 1.84, 1]} />
      <mesh geometry={nodes.Object_62.geometry} material={materials.tube} position={[-0.8, 0.286, -0.05]} rotation={[1.302, 0, 0]} scale={[1, 1.88, 1]} />
      <mesh geometry={nodes.Object_64.geometry} material={materials.tube} position={[0.8, 1.23, -0.06]} rotation={[-0.96, 0, 0]} scale={[1, 2.86, 1]} />
      <mesh geometry={nodes.Object_66.geometry} material={materials.tube} position={[0.8, 0.256, 0.92]} scale={[1, 0.51, 1]} />
      <mesh geometry={nodes.Object_68.geometry} material={materials.tube} position={[0.8, 0.926, -1]} scale={[1, 1.84, 1]} />
      <mesh geometry={nodes.Object_70.geometry} material={materials.tube} position={[0.8, 0.286, -0.05]} rotation={[1.302, 0, 0]} scale={[1, 1.88, 1]} />
      <mesh geometry={nodes.Object_72.geometry} material={materials.tube} position={[2.6, 1.23, -0.06]} rotation={[-0.96, 0, 0]} scale={[1, 2.86, 1]} />
      <mesh geometry={nodes.Object_74.geometry} material={materials.tube} position={[2.6, 0.256, 0.92]} scale={[1, 0.51, 1]} />
      <mesh geometry={nodes.Object_76.geometry} material={materials.tube} position={[2.6, 0.926, -1]} scale={[1, 1.84, 1]} />
      <mesh geometry={nodes.Object_78.geometry} material={materials.tube} position={[2.6, 0.286, -0.05]} rotation={[1.302, 0, 0]} scale={[1, 1.88, 1]} />
      <mesh geometry={nodes.Object_80.geometry} material={materials.Tube_clamp} position={[2.6, 1.844, -1]} scale={[1, 0.07, 1.18]} />
      <mesh geometry={nodes.Object_82.geometry} material={materials.Tube_clamp} position={[0.8, 0.039, -0.962]} rotation={[-2.159, 0, 0]} scale={[1, 0.07, 1.18]} />
      <mesh geometry={nodes.Object_84.geometry} material={materials.Tube_clamp} position={[2.6, 0.543, 0.857]} rotation={[-1.94, 0, -Math.PI]} scale={[1, 0.07, 1.18]} />
      <mesh geometry={nodes.Object_86.geometry} material={materials.Tube_clamp} position={[2.6, 0.039, -0.962]} rotation={[-2.159, 0, 0]} scale={[1, 0.07, 1.18]} />
      <mesh geometry={nodes.Object_88.geometry} material={materials.Tube_clamp} position={[-0.8, 0.039, -0.962]} rotation={[-2.159, 0, 0]} scale={[1, 0.07, 1.18]} />
      <mesh geometry={nodes.Object_90.geometry} material={materials.Tube_clamp} position={[-2.6, 0.039, -0.962]} rotation={[-2.159, 0, 0]} scale={[1, 0.07, 1.18]} />
      <mesh geometry={nodes.Object_92.geometry} material={materials.Tube_clamp} position={[0.8, 1.844, -1]} scale={[1, 0.07, 1.18]} />
      <mesh geometry={nodes.Object_94.geometry} material={materials.Tube_clamp} position={[0.8, 0.543, 0.857]} rotation={[-1.94, 0, -Math.PI]} scale={[1, 0.07, 1.18]} />
      <mesh geometry={nodes.Object_96.geometry} material={materials.Tube_clamp} position={[-0.8, 1.844, -1]} scale={[1, 0.07, 1.18]} />
      <mesh geometry={nodes.Object_98.geometry} material={materials.Tube_clamp} position={[-0.8, 0.543, 0.857]} rotation={[-1.94, 0, -Math.PI]} scale={[1, 0.07, 1.18]} />
      <mesh geometry={nodes.Object_100.geometry} material={materials.Tube_clamp} position={[-2.6, 1.844, -1]} scale={[1, 0.07, 1.18]} />
      <mesh geometry={nodes.Object_102.geometry} material={materials.Tube_clamp} position={[-2.6, 0.543, 0.857]} rotation={[-1.94, 0, -Math.PI]} scale={[1, 0.07, 1.18]} />
      <mesh geometry={nodes.Object_104.geometry} material={materials.Tube_clamp} position={[2.6, 0.499, 0.921]} scale={[1, 0.07, 1.18]} />
      <mesh geometry={nodes.Object_106.geometry} material={materials['Tube_clamp.001']} position={[0.8, 0.499, 0.921]} scale={[1, 0.07, 1.18]} />
      <mesh geometry={nodes.Object_108.geometry} material={materials['Tube_clamp.002']} position={[-0.8, 0.499, 0.921]} scale={[1, 0.07, 1.18]} />
      <mesh geometry={nodes.Object_110.geometry} material={materials['Tube_clamp.003']} position={[-2.6, 0.499, 0.921]} scale={[1, 0.07, 1.18]} />
      <mesh geometry={nodes.Object_112.geometry} material={materials['tube.001']} position={[1.7, 0.926, -1]} rotation={[0, 0, -0.833]} scale={[1, 2.42, 1]} />
      <mesh geometry={nodes.Object_114.geometry} material={materials['tube.002']} position={[-1.7, 0.996, -1]} rotation={[0, 0, -2.31]} scale={[1, 2.42, 1]} />
    </group>
  )
}

useGLTF.preload('/scene.gltf')
